language: python
python:
  - "2.7"

addons:
  postgresql: "9.3"


before_script:
  - cp imageboard/settings/local.travis.py imageboard/settings/local.py; psql -c 'create database django_imageboard;' -U postgres

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python manage.py migrate --settings=imageboard.settings.local; python manage.py test --settings=imageboard.settings.local
