language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python manage.py migrate --settings=imageboard.settings.local; python manage.py test --settings=imageboard.settings.local
